<?php
echo $this->doctype();
?>
<html lang="ru">
    <head>
        <meta charset="utf-8">

        <?php echo $this->headTitle('');
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array(
            'rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath() . '/img/ikz.ico')) 
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
       ?>

        <!-- Scripts -->
        <?php
        $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ?>

    </head>
    <body>
        <div id="root">THIS ROOT
        </div>
        <div>
             <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
